platform :ios, '13.0'

# CocoaPods analytics sends network requests synchronously impacting Flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings)
    raise "#{generated_xcode_build_settings} must exist. Run 'flutter pub get' before running pod install."
  end

  File.foreach(generated_xcode_build_settings) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings}."
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      definitions = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
      definitions = ['$(inherited)'] if definitions.nil?
      definitions = [definitions] unless definitions.is_a?(Array)
      definitions << 'PERMISSION_MICROPHONE=1' unless definitions.include?('PERMISSION_MICROPHONE=1')
      definitions << 'PERMISSION_SPEECH_RECOGNIZER=1' unless definitions.include?('PERMISSION_SPEECH_RECOGNIZER=1')
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
    end
  end
end
